Repository jquant/jai-sdk, pull requests merged in 2022-03, with the labels that each got.

#304 Parallel data insertion
  jai/jai.py
  jai/tests/test_zapi_applications.py
  jai/tests/test_zjai_basics.py
  jai/tests/test_zjai_errors.py
  jai/tests/test_zjai_models.py
  requirements.txt
Labels: documentation

#312 Create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation, enhancement

#311 Unix new function of preprocessing
  jai/preprocessing.py
Labels: priority 0, enhancement, new feature
